server {
    listen 80;
    server_name ${NGINX_HOST};

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ${NGINX_HOST};

    ssl_certificate /etc/letsencrypt/live/staging-bknd.zenith-blog.blog/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/staging-bknd.zenith-blog.blog/privkey.pem;

    root /var/www/blog/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        try_files $uri =404;
    }

    location ~ /\.ht {
        deny all;
    }
}
