name: STAGING

on:
  issue_comment:
    types: [created]

jobs:
  build-push-image:
    if: "contains(github.event.comment.body, '@staging') && github.event.issue.pull_request != null")
    runs-on: ubuntu-latest
    steps:
      - name: get PR branch
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('sha', pr.data.head.sha);
            core.setOutput('branch', pr.data.head.ref);
      - name: checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.sha }}

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.UAT_DOCKER_USERNAME }}
          password: ${{ secrets.UAT_DOCKER_TOKEN }}

      - name: build and push image
        run: |
          docker build \
            -t ${{ secrets.STAGING_DOCKER_USERNAME }}/application:uat \
            -t ${{ secrets.STAGING_DOCKER_USERNAME }}/application:${{ steps.pr.outputs.sha }} \
            .
          docker push ${{ secrets.STAGING_DOCKER_USERNAME }}/application:uat
          docker push ${{ secrets.STAGING_DOCKER_USERNAME }}/application:${{ steps.pr.outputs.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with: 
            host: ${{ secrets.STAGING_EC2_HOST }}
            username: ${{ secrets.STAGING_EC2_USERNAME }}
            key: ${{ secrets.STAGING_EC2_SSH_KEY }}
            script: |
                cd /var/www/application
                docker compose pull
                docker compose down -v
                docker compose up -d
                sleep 120
                docker compose ps
        
        comment:
           permissions:
              issues: write       
              pull-requests: write
           runs-on: ubuntu-latest
           name: comment
           needs: deploy
           env:
             HOST: ${{ secrets.STAGING_EC2_HOST }}
           steps:
             - name: add comment
               uses: actions/github-script@v7
               with:
                 script: |
                    github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: `Deployed to (${process.env.HOST})`
                    })
